export const GET_ERRORS = 'GET_ERRORS';

export const GET_SERVICES = 'GET_SERVICES';
export const POST_BOOKING = 'POST_BOOKING';
export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';
export const FETCH_SERVICE_DATES = 'FETCH_SERVICE_DATES';

// AUTHENTICATION
export const SET_CURRENT_PERSONNEL = 'SET_CURRENT_PERSONNEL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CREATE_SERVICE = 'CREATE_SERVICE';